export const codes = [
	{
		code: `100`,
		message: `Continue`,
		detail: `This interim response indicates that the client should continue the request or ignore the response if the request is already finished.`,
		class: `Informational response`,
	},
	{
		code: `101`,
		message: `Switching Protocols`,
		detail: `This code is sent in response to an Upgrade request header from the client and indicates the protocol the server is switching to.`,
		class: `Informational response`,
	},
	{
		code: `102`,
		message: `Processing (WebDAV)`,
		detail: `This code indicates that the server has received and is processing the request, but no response is available yet.`,
		class: `Informational response`,
	},
	{
		code: `103`,
		message: `Early Hints`,
		detail: `This status code is primarily intended to be used with the Link header, letting the user agent start preloading resources while the server prepares a response.`,
		class: `Informational response`,
	},
	{
		code: `200`,
		message: `OK`,
		detail: `The request succeeded. The result meaning of "success" depends on the HTTP method:
       - GET: The resource has been fetched and transmitted in the message body.
       - HEAD: The representation headers are included in the response without any message body.
       - PUT or POST: The resource describing the result of the action is transmitted in the message body.
       - TRACE: The message body contains the request message as received by the server.`,
		class: `Successful response`,
	},
	{
		code: `201`,
		message: `Created`,
		detail: `The request succeeded, and a new resource was created as a result. This is typically the response sent after POST requests, or some PUT requests.`,
		class: `Successful response`,
	},
	{
		code: `202`,
		message: `Accepted`,
		detail: `The request has been received but not yet acted upon. It is noncommittal, since there is no way in HTTP to later send an asynchronous response indicating the outcome of the request. It is intended for cases where another process or server handles the request, or for batch processing.`,
		class: `Successful response`,
	},
	{
		code: `203`,
		message: `Non-Authoritative Information`,
		detail: `This response code means the returned metadata is not exactly the same as is available from the origin server, but is collected from a local or a third-party copy. This is mostly used for mirrors or backups of another resource. Except for that specific case, the 200 OK response is preferred to this status.`,
		class: `Successful response`,
	},
	{
		code: `204`,
		message: `No Content`,
		detail: `There is no content to send for this request, but the headers may be useful. The user agent may update its cached headers for this resource with the new ones.`,
		class: `Successful response`,
	},
	{
		code: `205`,
		message: `Reset Content`,
		detail: `Tells the user agent to reset the document which sent this request.`,
		class: `Successful response`,
	},
	{
		code: `206`,
		message: `Partial Content`,
		detail: `This response code is used when the Range header is sent from the client to request only part of a resource.`,
		class: `Successful response`,
	},
	{
		code: `207`,
		message: `Multi-Status (WebDAV) `,
		detail: `Conveys information about multiple resources, for situations where multiple status codes might be appropriate.`,
		class: `Successful response`,
	},
	{
		code: `208`,
		message: `Already Reported (WebDAV) `,
		detail: `Used inside a <dav:propstat> response element to avoid repeatedly enumerating the internal members of multiple bindings to the same collection.`,
		class: `Successful response`,
	},
	{
		code: `226`,
		message: `IM Used (HTTP Delta encoding)`,
		detail: `The server has fulfilled a GET request for the resource, and the response is a representation of the result of one or more instance-manipulations applied to the current instance.`,
		class: `Successful response`,
	},
	{
		code: `300`,
		message: `Multiple Choices`,
		detail: `The request has more than one possible response. The user agent or user should choose one of them. (There is no standardized way of choosing one of the responses, but HTML links to the possibilities are recommended so the user can pick.)`,
		class: `Redirection message`,
	},
	{
		code: `301`,
		message: `Moved Permanently`,
		detail: `The URL of the requested resource has been changed permanently. The new URL is given in the response.`,
		class: `Redirection message`,
	},
	{
		code: `302`,
		message: `Found`,
		detail: `This response code means that the URI of requested resource has been changed temporarily. Further changes in the URI might be made in the future. Therefore, this same URI should be used by the client in future requests.`,
		class: `Redirection message`,
	},
	{
		code: `303`,
		message: `See Other`,
		detail: `The server sent this response to direct the client to get the requested resource at another URI with a GET request.`,
		class: `Redirection message`,
	},
	{
		code: `304`,
		message: `Not Modified`,
		detail: `This is used for caching purposes. It tells the client that the response has not been modified, so the client can continue to use the same cached version of the response.`,
		class: `Redirection message`,
	},
	{
		code: `305`,
		message: `Use Proxy Deprecated`,
		detail: `Defined in a previous version of the HTTP specification to indicate that a requested response must be accessed by a proxy. It has been deprecated due to security concerns regarding in-band configuration of a proxy.`,
		class: `Redirection message`,
	},
	{
		code: `306`,
		message: `Unused`,
		detail: `This response code is no longer used; it is just reserved. It was used in a previous version of the HTTP/1.1 specification.`,
		class: `Redirection message`,
	},
	{
		code: `307`,
		message: `Temporary Redirect`,
		detail: `The server sends this response to direct the client to get the requested resource at another URI with same method that was used in the prior request. This has the same semantics as the 302 Found HTTP response code, with the exception that the user agent must not change the HTTP method used: if a POST was used in the first request, a POST must be used in the second request.`,
		class: `Redirection message`,
	},
	{
		code: `308`,
		message: `Permanent Redirect`,
		detail: `This means that the resource is now permanently located at another URI, specified by the Location: HTTP Response header. This has the same semantics as the 301 Moved Permanently HTTP response code, with the exception that the user agent must not change the HTTP method used: if a POST was used in the first request, a POST must be used in the second request.`,
		class: `Redirection message`,
	},
	{
		code: ``,
		message: ``,
		detail: ``,
		class: `Client error response`,
	},
	{
		code: `400`,
		message: `Bad Request`,
		detail: `The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).`,
		class: `Client error response`,
	},
	{
		code: `401`,
		message: `Unauthorized`,
		detail: `Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response.`,
		class: `Client error response`,
	},
	{
		code: `402`,
		message: `Payment Required Experimental`,
		detail: `This response code is reserved for future use. The initial aim for creating this code was using it for digital payment systems, however this status code is used very rarely and no standard convention exists.`,
		class: `Client error response`,
	},
	{
		code: `403`,
		message: `Forbidden`,
		detail: `The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server.`,
		class: `Client error response`,
	},
	{
		code: `404`,
		message: `Not Found`,
		detail: `The server cannot find the requested resource. In the browser, this means the URL is not recognized. In an API, this can also mean that the endpoint is valid but the resource itself does not exist. Servers may also send this response instead of 403 Forbidden to hide the existence of a resource from an unauthorized client. This response code is probably the most well known due to its frequent occurrence on the web.`,
		class: `Client error response`,
	},
	{
		code: `405`,
		message: `Method Not Allowed`,
		detail: `The request method is known by the server but is not supported by the target resource. For example, an API may not allow calling DELETE to remove a resource.`,
		class: `Client error response`,
	},
	{
		code: `406`,
		message: `Not Acceptable`,
		detail: `This response is sent when the web server, after performing server-driven content negotiation, doesn't find any content that conforms to the criteria given by the user agent.`,
		class: `Client error response`,
	},
	{
		code: `407`,
		message: `Proxy Authentication Required`,
		detail: `This is similar to 401 Unauthorized but authentication is needed to be done by a proxy.`,
		class: `Client error response`,
	},
	{
		code: `408`,
		message: `Request Timeout`,
		detail: `This response is sent on an idle connection by some servers, even without any previous request by the client. It means that the server would like to shut down this unused connection. This response is used much more since some browsers, like Chrome, Firefox 27+, or IE9, use HTTP pre-connection mechanisms to speed up surfing. Also note that some servers merely shut down the connection without sending this message.`,
		class: `Client error response`,
	},
	{
		code: `409`,
		message: `Conflict`,
		detail: `This response is sent when a request conflicts with the current state of the server.`,
		class: `Client error response`,
	},
	{
		code: `410`,
		message: `Gone`,
		detail: `This response is sent when the requested content has been permanently deleted from server, with no forwarding address. Clients are expected to remove their caches and links to the resource. The HTTP specification intends this status code to be used for "limited-time, promotional services". APIs should not feel compelled to indicate resources that have been deleted with this status code.`,
		class: `Client error response`,
	},
	{
		code: `411`,
		message: `Length Required`,
		detail: `Server rejected the request because the Content-Length header field is not defined and the server requires it.`,
		class: `Client error response`,
	},
	{
		code: `412`,
		message: `Precondition Failed`,
		detail: `The client has indicated preconditions in its headers which the server does not meet.`,
		class: `Client error response`,
	},
	{
		code: `413`,
		message: `Payload Too Large`,
		detail: `Request entity is larger than limits defined by server; the server might close the connection or return an Retry-After header field.`,
		class: `Client error response`,
	},
	{
		code: `414`,
		message: `URI Too Long`,
		detail: `The URI requested by the client is longer than the server is willing to interpret.`,
		class: `Client error response`,
	},
	{
		code: `415`,
		message: `Unsupported Media Type`,
		detail: `The media format of the requested data is not supported by the server, so the server is rejecting the request.`,
		class: `Client error response`,
	},
	{
		code: `416`,
		message: `Range Not Satisfiable`,
		detail: `The range specified by the Range header field in the request can't be fulfilled; it's possible that the range is outside the size of the target URI's data.`,
		class: `Client error response`,
	},
	{
		code: `417`,
		message: `Expectation Failed`,
		detail: `This response code means the expectation indicated by the Expect request header field can't be met by the server.`,
		class: `Client error response`,
	},
	{
		code: `418`,
		message: `I'm a teapot`,
		detail: `The server refuses the attempt to brew coffee with a teapot.`,
		class: `Client error response`,
	},
	{
		code: `421`,
		message: `Misdirected Request`,
		detail: `The request was directed at a server that is not able to produce a response. This can be sent by a server that is not configured to produce responses for the combination of scheme and authority that are included in the request URI.`,
		class: `Client error response`,
	},
	{
		code: `422`,
		message: `Unprocessable Entity (WebDAV)`,
		detail: `The request was well-formed but was unable to be followed due to semantic errors.`,
		class: `Client error response`,
	},
	{
		code: `423`,
		message: `Locked (WebDAV)`,
		detail: `The resource that is being accessed is locked.`,
		class: `Client error response`,
	},
	{
		code: `424`,
		message: `Failed Dependency (WebDAV)`,
		detail: `The request failed due to failure of a previous request.`,
		class: `Client error response`,
	},
	{
		code: `425`,
		message: `Too Early`,
		detail: `Indicates that the server is unwilling to risk processing a request that might be replayed.`,
		class: `Client error response`,
	},
	{
		code: `426`,
		message: `Upgrade Required`,
		detail: `The server refuses to perform the request using the current protocol but might be willing to do so after the client upgrades to a different protocol. The server sends an Upgrade header in a 426 response to indicate the required protocol(s).`,
		class: `Client error response`,
	},
	{
		code: `428`,
		message: `Precondition Required`,
		detail: `The origin server requires the request to be conditional. Intended to prevent the 'lost update' problem, where a client GETs a resource's state, modifies it, and PUTs it back to the server, when meanwhile a third party has modified the state on the server, leading to a conflict.`,
		class: `Client error response`,
	},
	{
		code: `429`,
		message: `Too Many Requests`,
		detail: `The user has sent too many requests in a given amount of time ("rate limiting").`,
		class: `Client error response`,
	},
	{
		code: `431`,
		message: `Request Header Fields Too Large`,
		detail: `The server is unwilling to process the request because its header fields are too large. The request may be resubmitted after reducing the size of the request header fields.`,
		class: `Client error response`,
	},
	{
		code: `451`,
		message: `Unavailable For Legal Reasons`,
		detail: `The user agent requested a resource that cannot legally be provided, such as a web page censored by a government.`,
		class: `Client error response`,
	},
	{
		code: `500`,
		message: `Internal Server Error`,
		detail: `The server has encountered a situation it doesn't know how to handle.`,
		class: `Server error response`,
	},
	{
		code: `501`,
		message: `Not Implemented`,
		detail: `The request method is not supported by the server and cannot be handled. The only methods that servers are required to support (and therefore that must not return this code) are GET and HEAD.`,
		class: `Server error response`,
	},
	{
		code: `502`,
		message: `Bad Gateway`,
		detail: `This error response means that the server, while working as a gateway to get a response needed to handle the request, got an invalid response.`,
		class: `Server error response`,
	},
	{
		code: `503`,
		message: `Service Unavailable`,
		detail: `The server is not ready to handle the request. Common causes are a server that is down for maintenance or that is overloaded. Note that together with this response, a user-friendly page explaining the problem should be sent. This response should be used for temporary conditions and the Retry-After HTTP header should, if possible, contain the estimated time before the recovery of the service. The webmaster must also take care about the caching-related headers that are sent along with this response, as these temporary condition responses should usually not be cached.`,
		class: `Server error response`,
	},
	{
		code: `504`,
		message: `Gateway Timeout`,
		detail: `This error response is given when the server is acting as a gateway and cannot get a response in time.`,
		class: `Server error response`,
	},
	{
		code: `505`,
		message: `HTTP Version Not Supported`,
		detail: `The HTTP version used in the request is not supported by the server.`,
		class: `Server error response`,
	},
	{
		code: `506`,
		message: `Variant Also Negotiates`,
		detail: `The server has an internal configuration error: the chosen variant resource is configured to engage in transparent content negotiation itself, and is therefore not a proper end point in the negotiation process.`,
		class: `Server error response`,
	},
	{
		code: `507`,
		message: `Insufficient Storage (WebDAV)`,
		detail: `The method could not be performed on the resource because the server is unable to store the representation needed to successfully complete the request.`,
		class: `Server error response`,
	},
	{
		code: `508`,
		message: `Loop Detected (WebDAV)`,
		detail: `The server detected an infinite loop while processing the request.`,
		class: `Server error response`,
	},
	{
		code: `510`,
		message: `Not Extended`,
		detail: `Further extensions to the request are required for the server to fulfil it.`,
		class: `Server error response`,
	},
	{
		code: `511`,
		message: `Network Authentication Required`,
		detail: `The client needs to authenticate to gain network access. Intended for use by intercepting proxies used to control access to the network (e.g., "captive portals" used to require agreement to Terms of Service before granting full Internet access via a Wi-Fi hotspot)`,
		class: `Server error response`,
	},
]
