import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, test } from 'vite-plus/test';
import { codes } from './codes.js';

const og_dir = join(process.cwd(), 'static/og');

// The images are generated by `pnpm og` and committed.
describe('Open Graph images', () => {
	test('there is one for the home page', () => {
		expect(existsSync(join(og_dir, 'home.png'))).toBe(true);
	});

	test.each(codes.map((item) => item.code))(
		'there is one for %i',
		(code) => {
			expect(existsSync(join(og_dir, `${code}.png`))).toBe(true);
		},
	);
});
